---
title: "Con_Decon"
author: "Jeff Alexander"
date: "6/14/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(distr)
library(decon)
```


```{r}
X <- rnorm(1000,1,0.5)
Y <- rlnorm(1000,1.5,0.75)
Z <- X + Y
hist(X,freq=F,breaks=50, xlim=c(0,20))
hist(Y,freq=F,breaks=50, xlim=c(0,20))
hist(Z,freq=F,breaks=50, xlim=c(0,20))
```
```{r}
N <- Norm(mean=1, sd=0.5)
L <- Lnorm(meanlog=1.5, sdlog=0.75)
conv <- convpow(N+L, 1)
f.Z <- d(conv)
z <- seq(0,50,0.01)
hist(Z,freq=F,breaks=50, xlim=c(0,20))
lines(z,f.Z(z),lty=2,col="red")
```

## Deconvolution Correction with 1000 Observations
```{r}
n2 <- 1000
x2 <- c(rnorm(n2/2,-3,1),rnorm(n2/2,3,1))
sig2 <- 1.5
u2 <- rnorm(n2, sd=sig2)
w2 <- x2+u2
bw2 <- bw.dboot2(w2,sig=sig2, error="normal")
(f2 <-  DeconPdf(w2,sig2,error='normal' ,bw=bw2, fft=TRUE))
plot(f2,  col="red", lwd=3, lty=2, xlab="x", ylab="f(x)", main="", ylim=c(0,0.2), xlim=c(-15, 15))
lines(density(x2, from=min(w2), to=max(w2)), lwd=3, lty=1)
lines(density(w2), col="blue", lwd=3, lty=3)
legend(x = 5, y=0.2, c("Decon Data", "True Data", "Observed Data"), lty=c(2,1,3), lwd=c(3,3,3), col=c("red", "black", "blue"))
```


## Deconvolution Correction with 10000 Observations
```{r}

n2 <- 10000
x2 <- c(rnorm(n2/2,-3,1),rnorm(n2/2,3,1))
sig2 <- 1.5
u2 <- rnorm(n2, sd=sig2)
w2 <- x2+u2
bw2 <- bw.dboot2(w2,sig=sig2, error="normal")
(f2 <-  DeconPdf(w2,sig2,error='normal' ,bw=bw2, fft=TRUE))
plot(f2,  col="red", lwd=3, lty=2, xlab="x", ylab="f(x)", main="", ylim=c(0,0.2), xlim=c(-15, 15))
lines(density(x2, from=min(w2), to=max(w2)), lwd=3, lty=1)
lines(density(w2), col="blue", lwd=3, lty=3)
legend(x = 5, y=0.2, c("Decon Data", "True Data", "Observed Data"), lty=c(2,1,3), lwd=c(3,3,3), col=c("red", "black", "blue"))
```

## Deconvolution Correction with 200000 Observations
```{r}
n2 <- 200000
x2 <- c(rnorm(n2/2,-3,1),rnorm(n2/2,3,1))
sig2 <- 1.5
u2 <- rnorm(n2, sd=sig2)
w2 <- x2+u2
bw2 <- bw.dboot2(w2,sig=sig2, error="normal")
(f2 <-  DeconPdf(w2,sig2,error='normal' ,bw=bw2, fft=TRUE))
plot(f2,  col="red", lwd=3, lty=2, xlab="x", ylab="f(x)", main="", ylim=c(0,0.2), xlim=c(-15, 15))
lines(density(x2, from=min(w2), to=max(w2)), lwd=3, lty=1)
lines(density(w2), col="blue", lwd=3, lty=3)
legend(x = 5, y=0.2, c("Decon Data", "True Data", "Observed Data"), lty=c(2,1,3), lwd=c(3,3,3), col=c("red", "black", "blue"))
```

## Deconvolution Correction with 200000 Observations
```{r}
n2 <- 5000000
x2 <- c(rnorm(n2/2,-3,1),rnorm(n2/2,3,1))
sig2 <- 1.5
u2 <- rnorm(n2, sd=sig2)
w2 <- x2+u2
bw2 <- bw.dboot2(w2,sig=sig2, error="normal")
(f2 <-  DeconPdf(w2,sig2,error='normal' ,bw=bw2, fft=TRUE))
plot(f2,  col="red", lwd=3, lty=2, xlab="x", ylab="f(x)", main="", ylim=c(0,0.2), xlim=c(-15, 15))
lines(density(x2, from=min(w2), to=max(w2)), lwd=3, lty=1)
lines(density(w2), col="blue", lwd=3, lty=3)
legend(x = 5, y=0.2, c("Decon Data", "True Data", "Observed Data"), lty=c(2,1,3), lwd=c(3,3,3), col=c("red", "black", "blue"))
```


```{r}
n2 <- 10000
x2 <- c(rnorm(n2/2,-3,1),rnorm(n2/2,3,1))
sig2 <- 3
u2 <- rnorm(n2, sd=sig2)
w2 <- x2+u2
bw2 <- bw.dboot2(w2,sig=sig2, error="normal")
(f2 <-  DeconPdf(w2,sig2,error='normal' ,bw=bw2, fft=TRUE))
plot(f2,  col="red", lwd=3, lty=2, xlab="x", ylab="f(x)", main="", ylim=c(0,0.2), xlim=c(-15, 15))
lines(density(x2, from=min(w2), to=max(w2)), lwd=3, lty=1)
lines(density(w2), col="blue", lwd=3, lty=3)
legend(x = 5, y=0.2, c("Decon Data", "True Data", "Observed Data"), lty=c(2,1,3), lwd=c(3,3,3), col=c("red", "black", "blue"))
```

```{r}
n2 <- 5000000
x2 <- c(rnorm(n2/2,-3,1),rnorm(n2/2,3,1))
sig2 <- 3
u2 <- rnorm(n2, sd=sig2)
w2 <- x2+u2
bw2 <- bw.dboot2(w2,sig=sig2, error="normal")
(f2 <-  DeconPdf(w2,sig2,error='normal' ,bw=bw2, fft=TRUE))
plot(f2,  col="red", lwd=3, lty=2, xlab="x", ylab="f(x)", main="", ylim=c(0,0.2), xlim=c(-15, 15))
lines(density(x2, from=min(w2), to=max(w2)), lwd=3, lty=1)
lines(density(w2), col="blue", lwd=3, lty=3)
legend(x = 5, y=0.2, c("Decon Data", "True Data", "Observed Data"), lty=c(2,1,3), lwd=c(3,3,3), col=c("red", "black", "blue"))
```
```{r}
sig2 <- 1
u2 <- rnorm(n2, sd=sig2)
u3 <- rnorm(n2, sd=4)


n2 <- 10000
x <- c(rnorm(n2, 0, 0.5), rnorm(n2, 0, 3))
y <- c(rnorm(n2, 0, 0.5), rnorm(n2, 0, 3))


x2 <- x + u2
y2 <- y + u2

x3 <- x + u3
y3 <- y + u3

hist(sqrt(x^2 + y^2), breaks=c(0, seq(0.5, 20, by=0.5), 100), xlim=c(0, 20))
hist(sqrt(x2^2 + y2^2), breaks=c(0, seq(0.5, 20, by=0.5), 100), xlim=c(0, 20))
hist(sqrt(x3^2 + y3^2), breaks=c(0, seq(0.5, 20, by=0.5), 100), xlim=c(0, 20))

```
